//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 10:28:12 PM CST 
//


package com.itwheel.edigate.po;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.itwheel.edigate.po package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.itwheel.edigate.po
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DOCUMENT }
     * 
     */
    public DOCUMENT createDOCUMENT() {
        return new DOCUMENT();
    }

    /**
     * Create an instance of {@link PO }
     * 
     */
    public PO createPO() {
        return new PO();
    }

    /**
     * Create an instance of {@link PO.POITEMS }
     * 
     */
    public PO.POITEMS createPOPOITEMS() {
        return new PO.POITEMS();
    }

    /**
     * Create an instance of {@link PO.POITEMS.POITEM }
     * 
     */
    public PO.POITEMS.POITEM createPOPOITEMSPOITEM() {
        return new PO.POITEMS.POITEM();
    }

    /**
     * Create an instance of {@link PO.POITEMS.POITEM.POQTYS }
     * 
     */
    public PO.POITEMS.POITEM.POQTYS createPOPOITEMSPOITEMPOQTYS() {
        return new PO.POITEMS.POITEM.POQTYS();
    }

    /**
     * Create an instance of {@link PO.POAPPROVALS }
     * 
     */
    public PO.POAPPROVALS createPOPOAPPROVALS() {
        return new PO.POAPPROVALS();
    }

    /**
     * Create an instance of {@link PO.POTERMS }
     * 
     */
    public PO.POTERMS createPOPOTERMS() {
        return new PO.POTERMS();
    }

    /**
     * Create an instance of {@link PO.POFEES }
     * 
     */
    public PO.POFEES createPOPOFEES() {
        return new PO.POFEES();
    }

    /**
     * Create an instance of {@link DOCUMENT.POS }
     * 
     */
    public DOCUMENT.POS createDOCUMENTPOS() {
        return new DOCUMENT.POS();
    }

    /**
     * Create an instance of {@link INVNBASEITEM }
     * 
     */
    public INVNBASEITEM createINVNBASEITEM() {
        return new INVNBASEITEM();
    }

    /**
     * Create an instance of {@link PO.POITEMS.POITEM.POQTYS.POQTY }
     * 
     */
    public PO.POITEMS.POITEM.POQTYS.POQTY createPOPOITEMSPOITEMPOQTYSPOQTY() {
        return new PO.POITEMS.POITEM.POQTYS.POQTY();
    }

    /**
     * Create an instance of {@link PO.POAPPROVALS.POAPPROVAL }
     * 
     */
    public PO.POAPPROVALS.POAPPROVAL createPOPOAPPROVALSPOAPPROVAL() {
        return new PO.POAPPROVALS.POAPPROVAL();
    }

    /**
     * Create an instance of {@link PO.POTERMS.POTERM }
     * 
     */
    public PO.POTERMS.POTERM createPOPOTERMSPOTERM() {
        return new PO.POTERMS.POTERM();
    }

    /**
     * Create an instance of {@link PO.POFEES.POFEE }
     * 
     */
    public PO.POFEES.POFEE createPOPOFEESPOFEE() {
        return new PO.POFEES.POFEE();
    }

}
