//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 10:27:39 PM CST 
//


package com.itwheel.edigate.asn;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.itwheel.edigate.asn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.itwheel.edigate.asn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DOCUMENT }
     * 
     */
    public DOCUMENT createDOCUMENT() {
        return new DOCUMENT();
    }

    /**
     * Create an instance of {@link VOUCHER }
     * 
     */
    public VOUCHER createVOUCHER() {
        return new VOUCHER();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUITEMS }
     * 
     */
    public VOUCHER.VOUITEMS createVOUCHERVOUITEMS() {
        return new VOUCHER.VOUITEMS();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUAPPROVALS }
     * 
     */
    public VOUCHER.VOUAPPROVALS createVOUCHERVOUAPPROVALS() {
        return new VOUCHER.VOUAPPROVALS();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUTERMS }
     * 
     */
    public VOUCHER.VOUTERMS createVOUCHERVOUTERMS() {
        return new VOUCHER.VOUTERMS();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUFEES }
     * 
     */
    public VOUCHER.VOUFEES createVOUCHERVOUFEES() {
        return new VOUCHER.VOUFEES();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUCOMMENTS }
     * 
     */
    public VOUCHER.VOUCOMMENTS createVOUCHERVOUCOMMENTS() {
        return new VOUCHER.VOUCOMMENTS();
    }

    /**
     * Create an instance of {@link DOCUMENT.VOUCHERS }
     * 
     */
    public DOCUMENT.VOUCHERS createDOCUMENTVOUCHERS() {
        return new DOCUMENT.VOUCHERS();
    }

    /**
     * Create an instance of {@link INVNBASEITEM }
     * 
     */
    public INVNBASEITEM createINVNBASEITEM() {
        return new INVNBASEITEM();
    }

    /**
     * Create an instance of {@link VENDINVOICE }
     * 
     */
    public VENDINVOICE createVENDINVOICE() {
        return new VENDINVOICE();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUITEMS.VOUITEM }
     * 
     */
    public VOUCHER.VOUITEMS.VOUITEM createVOUCHERVOUITEMSVOUITEM() {
        return new VOUCHER.VOUITEMS.VOUITEM();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUAPPROVALS.VOUAPPROVAL }
     * 
     */
    public VOUCHER.VOUAPPROVALS.VOUAPPROVAL createVOUCHERVOUAPPROVALSVOUAPPROVAL() {
        return new VOUCHER.VOUAPPROVALS.VOUAPPROVAL();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUTERMS.VOUTERM }
     * 
     */
    public VOUCHER.VOUTERMS.VOUTERM createVOUCHERVOUTERMSVOUTERM() {
        return new VOUCHER.VOUTERMS.VOUTERM();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUFEES.VOUFEE }
     * 
     */
    public VOUCHER.VOUFEES.VOUFEE createVOUCHERVOUFEESVOUFEE() {
        return new VOUCHER.VOUFEES.VOUFEE();
    }

    /**
     * Create an instance of {@link VOUCHER.VOUCOMMENTS.VOUCOMMENT }
     * 
     */
    public VOUCHER.VOUCOMMENTS.VOUCOMMENT createVOUCHERVOUCOMMENTSVOUCOMMENT() {
        return new VOUCHER.VOUCOMMENTS.VOUCOMMENT();
    }

}
