//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 10:27:39 PM CST 
//


package com.itwheel.edigate.asn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VEND_INVOICE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VEND_INVOICE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="vend_invc_id" type="{}integerNullable" />
 *       &lt;attribute name="sbs_no" use="required" type="{}integerNullable" />
 *       &lt;attribute name="vend_code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vend_invc_no" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vend_invc_date" type="{}dateTimeNullable" />
 *       &lt;attribute name="vend_invc_amt" type="{}doubleNullable" />
 *       &lt;attribute name="empl_id" type="{}integerNullable" />
 *       &lt;attribute name="created_date" use="required" type="{}dateTimeNullable" />
 *       &lt;attribute name="modified_date" use="required" type="{}dateTimeNullable" />
 *       &lt;attribute name="cms_post_date" type="{}dateTimeNullable" />
 *       &lt;attribute name="resolvby_id" type="{}integerNullable" />
 *       &lt;attribute name="resolv_date" type="{}dateTimeNullable" />
 *       &lt;attribute name="approvby_id" type="{}integerNullable" />
 *       &lt;attribute name="approv_date" type="{}dateTimeNullable" />
 *       &lt;attribute name="po_no" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="notes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modifiedby_id" type="{}integerNullable" />
 *       &lt;attribute name="createdby_id" type="{}integerNullable" />
 *       &lt;attribute name="empl_sbs_no" type="{}integerNullable" />
 *       &lt;attribute name="empl_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resolvby_sbs_no" type="{}integerNullable" />
 *       &lt;attribute name="resolvby_empl_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="approvby_sbs_no" type="{}integerNullable" />
 *       &lt;attribute name="approvby_empl_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modifiedby_sbs_no" type="{}integerNullable" />
 *       &lt;attribute name="modifiedby_empl_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="createdby_sbs_no" type="{}integerNullable" />
 *       &lt;attribute name="createdby_empl_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VEND_INVOICE")
public class VENDINVOICE {

    @XmlAttribute(name = "vend_invc_id")
    protected String vendInvcId;
    @XmlAttribute(name = "sbs_no", required = true)
    protected String sbsNo;
    @XmlAttribute(name = "vend_code", required = true)
    protected String vendCode;
    @XmlAttribute(name = "vend_invc_no", required = true)
    protected String vendInvcNo;
    @XmlAttribute(name = "vend_invc_date")
    protected String vendInvcDate;
    @XmlAttribute(name = "vend_invc_amt")
    protected String vendInvcAmt;
    @XmlAttribute(name = "empl_id")
    protected String emplId;
    @XmlAttribute(name = "created_date", required = true)
    protected String createdDate;
    @XmlAttribute(name = "modified_date", required = true)
    protected String modifiedDate;
    @XmlAttribute(name = "cms_post_date")
    protected String cmsPostDate;
    @XmlAttribute(name = "resolvby_id")
    protected String resolvbyId;
    @XmlAttribute(name = "resolv_date")
    protected String resolvDate;
    @XmlAttribute(name = "approvby_id")
    protected String approvbyId;
    @XmlAttribute(name = "approv_date")
    protected String approvDate;
    @XmlAttribute(name = "po_no")
    protected String poNo;
    @XmlAttribute(name = "notes")
    protected String notes;
    @XmlAttribute(name = "modifiedby_id")
    protected String modifiedbyId;
    @XmlAttribute(name = "createdby_id")
    protected String createdbyId;
    @XmlAttribute(name = "empl_sbs_no")
    protected String emplSbsNo;
    @XmlAttribute(name = "empl_name")
    protected String emplName;
    @XmlAttribute(name = "resolvby_sbs_no")
    protected String resolvbySbsNo;
    @XmlAttribute(name = "resolvby_empl_name")
    protected String resolvbyEmplName;
    @XmlAttribute(name = "approvby_sbs_no")
    protected String approvbySbsNo;
    @XmlAttribute(name = "approvby_empl_name")
    protected String approvbyEmplName;
    @XmlAttribute(name = "modifiedby_sbs_no")
    protected String modifiedbySbsNo;
    @XmlAttribute(name = "modifiedby_empl_name")
    protected String modifiedbyEmplName;
    @XmlAttribute(name = "createdby_sbs_no")
    protected String createdbySbsNo;
    @XmlAttribute(name = "createdby_empl_name")
    protected String createdbyEmplName;

    /**
     * Gets the value of the vendInvcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendInvcId() {
        return vendInvcId;
    }

    /**
     * Sets the value of the vendInvcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendInvcId(String value) {
        this.vendInvcId = value;
    }

    /**
     * Gets the value of the sbsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSbsNo() {
        return sbsNo;
    }

    /**
     * Sets the value of the sbsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSbsNo(String value) {
        this.sbsNo = value;
    }

    /**
     * Gets the value of the vendCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendCode() {
        return vendCode;
    }

    /**
     * Sets the value of the vendCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendCode(String value) {
        this.vendCode = value;
    }

    /**
     * Gets the value of the vendInvcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendInvcNo() {
        return vendInvcNo;
    }

    /**
     * Sets the value of the vendInvcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendInvcNo(String value) {
        this.vendInvcNo = value;
    }

    /**
     * Gets the value of the vendInvcDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendInvcDate() {
        return vendInvcDate;
    }

    /**
     * Sets the value of the vendInvcDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendInvcDate(String value) {
        this.vendInvcDate = value;
    }

    /**
     * Gets the value of the vendInvcAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendInvcAmt() {
        return vendInvcAmt;
    }

    /**
     * Sets the value of the vendInvcAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendInvcAmt(String value) {
        this.vendInvcAmt = value;
    }

    /**
     * Gets the value of the emplId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplId() {
        return emplId;
    }

    /**
     * Sets the value of the emplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplId(String value) {
        this.emplId = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedDate(String value) {
        this.modifiedDate = value;
    }

    /**
     * Gets the value of the cmsPostDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmsPostDate() {
        return cmsPostDate;
    }

    /**
     * Sets the value of the cmsPostDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmsPostDate(String value) {
        this.cmsPostDate = value;
    }

    /**
     * Gets the value of the resolvbyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolvbyId() {
        return resolvbyId;
    }

    /**
     * Sets the value of the resolvbyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolvbyId(String value) {
        this.resolvbyId = value;
    }

    /**
     * Gets the value of the resolvDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolvDate() {
        return resolvDate;
    }

    /**
     * Sets the value of the resolvDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolvDate(String value) {
        this.resolvDate = value;
    }

    /**
     * Gets the value of the approvbyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovbyId() {
        return approvbyId;
    }

    /**
     * Sets the value of the approvbyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovbyId(String value) {
        this.approvbyId = value;
    }

    /**
     * Gets the value of the approvDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovDate() {
        return approvDate;
    }

    /**
     * Sets the value of the approvDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovDate(String value) {
        this.approvDate = value;
    }

    /**
     * Gets the value of the poNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoNo() {
        return poNo;
    }

    /**
     * Sets the value of the poNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoNo(String value) {
        this.poNo = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the modifiedbyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedbyId() {
        return modifiedbyId;
    }

    /**
     * Sets the value of the modifiedbyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedbyId(String value) {
        this.modifiedbyId = value;
    }

    /**
     * Gets the value of the createdbyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedbyId() {
        return createdbyId;
    }

    /**
     * Sets the value of the createdbyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedbyId(String value) {
        this.createdbyId = value;
    }

    /**
     * Gets the value of the emplSbsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplSbsNo() {
        return emplSbsNo;
    }

    /**
     * Sets the value of the emplSbsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplSbsNo(String value) {
        this.emplSbsNo = value;
    }

    /**
     * Gets the value of the emplName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplName() {
        return emplName;
    }

    /**
     * Sets the value of the emplName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplName(String value) {
        this.emplName = value;
    }

    /**
     * Gets the value of the resolvbySbsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolvbySbsNo() {
        return resolvbySbsNo;
    }

    /**
     * Sets the value of the resolvbySbsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolvbySbsNo(String value) {
        this.resolvbySbsNo = value;
    }

    /**
     * Gets the value of the resolvbyEmplName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolvbyEmplName() {
        return resolvbyEmplName;
    }

    /**
     * Sets the value of the resolvbyEmplName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolvbyEmplName(String value) {
        this.resolvbyEmplName = value;
    }

    /**
     * Gets the value of the approvbySbsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovbySbsNo() {
        return approvbySbsNo;
    }

    /**
     * Sets the value of the approvbySbsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovbySbsNo(String value) {
        this.approvbySbsNo = value;
    }

    /**
     * Gets the value of the approvbyEmplName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovbyEmplName() {
        return approvbyEmplName;
    }

    /**
     * Sets the value of the approvbyEmplName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovbyEmplName(String value) {
        this.approvbyEmplName = value;
    }

    /**
     * Gets the value of the modifiedbySbsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedbySbsNo() {
        return modifiedbySbsNo;
    }

    /**
     * Sets the value of the modifiedbySbsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedbySbsNo(String value) {
        this.modifiedbySbsNo = value;
    }

    /**
     * Gets the value of the modifiedbyEmplName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedbyEmplName() {
        return modifiedbyEmplName;
    }

    /**
     * Sets the value of the modifiedbyEmplName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedbyEmplName(String value) {
        this.modifiedbyEmplName = value;
    }

    /**
     * Gets the value of the createdbySbsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedbySbsNo() {
        return createdbySbsNo;
    }

    /**
     * Sets the value of the createdbySbsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedbySbsNo(String value) {
        this.createdbySbsNo = value;
    }

    /**
     * Gets the value of the createdbyEmplName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedbyEmplName() {
        return createdbyEmplName;
    }

    /**
     * Sets the value of the createdbyEmplName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedbyEmplName(String value) {
        this.createdbyEmplName = value;
    }

}
